#ifndef MAIN_H
#define MAIN_H

#include <stdint.h>
#include "esp_attr.h"  // for RTC_DATA_ATTR if needed

// Enum definition for finite states
typedef enum {
    SENDING_STATE,
    RECEIVING_STATE,
    SLEEP_STATE
} FINITE_STATES;

// Global variables (defined in main.c)
extern FINITE_STATES currentState;
extern FINITE_STATES saved_mode;

// Telemetry entry structure
typedef struct {
    const char* name;
    float value;
    uint8_t type; // 0 = float, 1 = uint8, 2 = int16, etc. if needed
} telemetry_entry_t;

// Enum for telemetry indices (makes it easier to access)
typedef enum {
    TELEM_EMETER_CURRENT,
    TELEM_EMETER_VOLTAGE,
    TELEM_MCM_MOTOR_SPEED,
    TELEM_MCM_DC_BUS_CURRENT,
    TELEM_MCM_DC_BUS_VOLTAGE,
    TELEM_MCM_INT_INVERT_ENABLE_STATE,
    TELEM_MCM_INT_INVERTER_STATE,
    TELEM_MCM_TORQUE_FEEDBACK,
    TELEM_MCM_COMMANDED_TORQUE,
    TELEM_MCM_TORQUE_LIMIT_COMMAND,
    TELEM_MCM_SPEED_MODE_ENABLE,
    TELEM_TPS0_CALIB_MIN,
    TELEM_TPS0_CALIB_MAX,
    TELEM_VCU_WSS_FL_S,
    TELEM_VCU_WSS_FR_S,
    TELEM_VCU_WSS_RL_S,
    TELEM_VCU_WSS_RR_S,
    TELEM_VCU_FAULT_TPS_OUTOFRANGE,
    TELEM_VCU_FAULT_BPS_OUTOFRANGE,
    TELEM_VCU_FAULT_TPS_POWERFAILURE,
    TELEM_VCU_FAULT_BPS_POWERFAILURE,
    TELEM_VCU_FAULT_TPS_SIGNALFAILURE,
    TELEM_VCU_FAULT_BPS_SIGNALFAILURE,
    TELEM_VCU_FAULT_TPS_NOTCALIBRATED,
    TELEM_VCU_FAULT_BPS_NOTCALIBRATED,
    TELEM_VCU_FAULT_TPS_OUTOFSYNC,
    TELEM_VCU_FAULT_TPSBPS_IMPLAUSIBLE,
    TELEM_VCU_FAULT_BSPD_SOFTFAULT,
    TELEM_VCU_FAULT_LVS_BATTERYEMPTY,
    TELEM_VCU_WARNING_LVS_BATTERYLOW,
    TELEM_VCU_NOTICE_HVIL_TERMSENSELOST,
    TELEM_SPEED_KPH,
    TELEM_LC_READY,
    TELEM_LC_STATUS,
    TELEM_TORQUE,
    TELEM_SLIP_RATIO,
    TELEM_START_TORQUE,
    TELEM_STEERING_ANGLE,
    TELEM_DRS_ENABLE,
    TELEM_DRS_MODE,
    TELEM_BMS_PACK_VOLTAGE,
    TELEM_BMS_BALANCING_STATE,
    TELEM_BMS_PACK_HIGH_VOLT_WARNING,
    TELEM_BMS_PACK_LOW_VOLT_WARNING,
    TELEM_BMS_CELL_LOW_VOLT_WARNING,
    TELEM_BMS_CELL_HIGH_VOLT_WARNING,
    TELEM_BMS_CELL_HIGH_TEMP_WARNING,
    TELEM_BMS_CELL_LOW_TEMP_WARNING,
    TELEM_BMS_CELL_VOLT_IMBALANCE_WARNING,
    TELEM_BMS_PACK_HIGH_VOLT_FAULT,
    TELEM_BMS_PACK_LOW_VOLT_FAULT,
    TELEM_BMS_CELL_LOW_VOLT_FAULT,
    TELEM_BMS_CELL_HIGH_VOLT_FAULT,
    TELEM_BMS_CELL_HIGH_TEMP_FAULT,
    TELEM_BMS_CELL_VOLT_IMBALANCE_FAULT,
    TELEM_BMS_BALACING_END_FAULT,
    TELEM_LOWEST_CELL_TEMPERATURE,
    TELEM_HIGHEST_CELL_TEMPERATURE,
    TELEM_LOWEST_CELL_VOLTAGE,
    TELEM_HIGHEST_CELL_VOLTAGE,
    TELEM_TEMPERATURE,
    TELEM_HUMIDITY,
    TELEM_RAW_IMU_READING,
    TELEM_COUNT // Total number of telemetry entries
} telemetry_index_t;

// Global declaration
extern telemetry_entry_t telemetry_data[TELEM_COUNT];

// Function declarations
void init_telemetry_data(void);
void update_telemetry_value_by_name(const char* name, float value);
float get_telemetry_value_by_name(const char* name);
void print_all_telemetry(void);

#endif // MAIN_H
